source orders_src
{
    type            = pgsql
    sql_host        = postgres
    sql_user        = app
    sql_pass        = app
    sql_db          = app
    sql_port        = 5432
    sql_query       = SELECT id, name, client_name, client_surname, email, description FROM orders
}

index orders
{
    source          = orders_src
    path            = /var/lib/manticore/orders
}

searchd
{
    listen          = 9306:mysql41
    listen          = 9308:http
    log             = /var/lib/manticore/searchd.log
    query_log       = /var/lib/manticore/query.log
    pid_file        = /var/lib/manticore/searchd.pid
    workers         = threads
    binlog_path     = /var/lib/manticore
}
