api_orders_search:
  path: /api/v1/orders/search
  controller: App\Controller\OrderSearchController
  methods: [GET]

api_orders_stats:
  path: /api/v1/orders/stats
  controller: App\Controller\OrderStatsController::run
  methods: [GET]

api_order_show:
    path: /api/v1/orders/{hash}
    controller: App\Controller\OrderController::run
    methods: [GET]
    requirements:
        hash: '[a-zA-Z0-9_-]+'

api_price:
  path: /api/v1/price
  controller: App\Controller\PriceController::run
  methods: [GET]

api_soap_orders:
  path: /api/v1/soap/orders
  controller: App\Controller\SoapController::run
  methods: [GET, POST]

app_swagger_ui:
  path: /api/doc
  controller: App\Controller\SwaggerController::ui
  methods: [GET]

app_swagger_ui_v1:
  path: /api/v1/doc
  controller: App\Controller\SwaggerController::ui
  methods: [GET]

app_swagger_json:
  path: /api/doc.json
  controller: App\Controller\SwaggerController::json
  methods: [GET]

app_swagger_json_v1:
  path: /api/v1/doc.json
  controller: App\Controller\SwaggerController::json
  methods: [GET]

controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
