api_orders_search:
  path: /api/v1/orders/search
  controller: App\Controller\OrderSearchController
  methods: [GET]

api_orders_stats:
  path: /api/v1/orders/stats
  controller: App\Controller\OrderStatsController::run
  methods: [GET]

api_order_show:
    path: /api/v1/orders/{hash}
    controller: App\Controller\OrderController::run
    methods: [GET]
    requirements:
        hash: '[a-zA-Z0-9_-]+'

api_price:
  path: /api/v1/price
  controller: App\Controller\PriceController::run
  methods: [GET]

api_soap_orders:
  path: /api/v1/soap/orders
  controller: App\Controller\SoapController::run
  methods: [GET, POST]

controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
