parameters: {}

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    Nelmio\ApiDocBundle\RouteDescriber\RouteDescriberInterface:
      tags: ['nelmio_api_doc.route_describer']

  App\:
    resource: '../src/'

    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']

